"""서울 상권 CSV(한글 헤더) → ORM 영문 컬럼 매핑.

3NF 적재 스크립트(scripts/ingest_seoul_3nf.py)가 사용한다. 차원 속성 키
(trdar_div_code/trdar_div_name/trdar_name/service_name/change_indicator_name)는
스크립트가 DIM_KEYS로 제거하므로 여기서는 원본 매핑을 그대로 보존한다.
"""

ESTIMATED_SALES_COLUMN_MAP: dict[str, str] = {
    "기준_년분기_코드": "year_quarter",
    "상권_구분_코드": "trdar_div_code",
    "상권_구분_코드_명": "trdar_div_name",
    "상권_코드": "trdar_code",
    "상권_코드_명": "trdar_name",
    "서비스_업종_코드": "service_code",
    "서비스_업종_코드_명": "service_name",
    "당월_매출_금액": "monthly_sales_amount",
    "당월_매출_건수": "monthly_sales_count",
    "주중_매출_금액": "weekday_sales_amount",
    "주말_매출_금액": "weekend_sales_amount",
    "월요일_매출_금액": "mon_sales_amount",
    "화요일_매출_금액": "tue_sales_amount",
    "수요일_매출_금액": "wed_sales_amount",
    "목요일_매출_금액": "thu_sales_amount",
    "금요일_매출_금액": "fri_sales_amount",
    "토요일_매출_금액": "sat_sales_amount",
    "일요일_매출_금액": "sun_sales_amount",
    "시간대_00~06_매출_금액": "time_00_06_sales_amount",
    "시간대_06~11_매출_금액": "time_06_11_sales_amount",
    "시간대_11~14_매출_금액": "time_11_14_sales_amount",
    "시간대_14~17_매출_금액": "time_14_17_sales_amount",
    "시간대_17~21_매출_금액": "time_17_21_sales_amount",
    "시간대_21~24_매출_금액": "time_21_24_sales_amount",
    "남성_매출_금액": "male_sales_amount",
    "여성_매출_금액": "female_sales_amount",
    "연령대_10_매출_금액": "age_10_sales_amount",
    "연령대_20_매출_금액": "age_20_sales_amount",
    "연령대_30_매출_금액": "age_30_sales_amount",
    "연령대_40_매출_금액": "age_40_sales_amount",
    "연령대_50_매출_금액": "age_50_sales_amount",
    "연령대_60_이상_매출_금액": "age_60_plus_sales_amount",
    "주중_매출_건수": "weekday_sales_count",
    "주말_매출_건수": "weekend_sales_count",
    "월요일_매출_건수": "mon_sales_count",
    "화요일_매출_건수": "tue_sales_count",
    "수요일_매출_건수": "wed_sales_count",
    "목요일_매출_건수": "thu_sales_count",
    "금요일_매출_건수": "fri_sales_count",
    "토요일_매출_건수": "sat_sales_count",
    "일요일_매출_건수": "sun_sales_count",
    "시간대_건수~06_매출_건수": "time_00_06_sales_count",
    "시간대_건수~11_매출_건수": "time_06_11_sales_count",
    "시간대_건수~14_매출_건수": "time_11_14_sales_count",
    "시간대_건수~17_매출_건수": "time_14_17_sales_count",
    "시간대_건수~21_매출_건수": "time_17_21_sales_count",
    "시간대_건수~24_매출_건수": "time_21_24_sales_count",
    "남성_매출_건수": "male_sales_count",
    "여성_매출_건수": "female_sales_count",
    "연령대_10_매출_건수": "age_10_sales_count",
    "연령대_20_매출_건수": "age_20_sales_count",
    "연령대_30_매출_건수": "age_30_sales_count",
    "연령대_40_매출_건수": "age_40_sales_count",
    "연령대_50_매출_건수": "age_50_sales_count",
    "연령대_60_이상_매출_건수": "age_60_plus_sales_count",
}

STORE_COLUMN_MAP: dict[str, str] = {
    "기준_년분기_코드": "year_quarter",
    "상권_구분_코드": "trdar_div_code",
    "상권_구분_코드_명": "trdar_div_name",
    "상권_코드": "trdar_code",
    "상권_코드_명": "trdar_name",
    "서비스_업종_코드": "service_code",
    "서비스_업종_코드_명": "service_name",
    "점포_수": "store_count",
    "유사_업종_점포_수": "similar_industry_store_count",
    "개업_율": "opening_rate",
    "개업_점포_수": "opening_store_count",
    "폐업_률": "closure_rate",
    "폐업_점포_수": "closure_store_count",
    "프랜차이즈_점포_수": "franchise_store_count",
}

FLOATING_POPULATION_COLUMN_MAP: dict[str, str] = {
    "기준_년분기_코드": "year_quarter",
    "상권_구분_코드": "trdar_div_code",
    "상권_구분_코드_명": "trdar_div_name",
    "상권_코드": "trdar_code",
    "상권_코드_명": "trdar_name",
    "총_유동인구_수": "total_floating_pop",
    "남성_유동인구_수": "male_floating_pop",
    "여성_유동인구_수": "female_floating_pop",
    "연령대_10_유동인구_수": "age_10_floating_pop",
    "연령대_20_유동인구_수": "age_20_floating_pop",
    "연령대_30_유동인구_수": "age_30_floating_pop",
    "연령대_40_유동인구_수": "age_40_floating_pop",
    "연령대_50_유동인구_수": "age_50_floating_pop",
    "연령대_60_이상_유동인구_수": "age_60_plus_floating_pop",
    "시간대_00_06_유동인구_수": "time_00_06_floating_pop",
    "시간대_06_11_유동인구_수": "time_06_11_floating_pop",
    "시간대_11_14_유동인구_수": "time_11_14_floating_pop",
    "시간대_14_17_유동인구_수": "time_14_17_floating_pop",
    "시간대_17_21_유동인구_수": "time_17_21_floating_pop",
    "시간대_21_24_유동인구_수": "time_21_24_floating_pop",
    "월요일_유동인구_수": "mon_floating_pop",
    "화요일_유동인구_수": "tue_floating_pop",
    "수요일_유동인구_수": "wed_floating_pop",
    "목요일_유동인구_수": "thu_floating_pop",
    "금요일_유동인구_수": "fri_floating_pop",
    "토요일_유동인구_수": "sat_floating_pop",
    "일요일_유동인구_수": "sun_floating_pop",
}

RESIDENT_POPULATION_COLUMN_MAP: dict[str, str] = {
    "기준_년분기_코드": "year_quarter",
    "상권_구분_코드": "trdar_div_code",
    "상권_구분_코드_명": "trdar_div_name",
    "상권_코드": "trdar_code",
    "상권_코드_명": "trdar_name",
    "총_상주인구_수": "total_resident_pop",
    "남성_상주인구_수": "male_resident_pop",
    "여성_상주인구_수": "female_resident_pop",
    "연령대_10_상주인구_수": "age_10_resident_pop",
    "연령대_20_상주인구_수": "age_20_resident_pop",
    "연령대_30_상주인구_수": "age_30_resident_pop",
    "연령대_40_상주인구_수": "age_40_resident_pop",
    "연령대_50_상주인구_수": "age_50_resident_pop",
    "연령대_60_이상_상주인구_수": "age_60_plus_resident_pop",
    "남성연령대_10_상주인구_수": "male_age_10_resident_pop",
    "남성연령대_20_상주인구_수": "male_age_20_resident_pop",
    "남성연령대_30_상주인구_수": "male_age_30_resident_pop",
    "남성연령대_40_상주인구_수": "male_age_40_resident_pop",
    "남성연령대_50_상주인구_수": "male_age_50_resident_pop",
    "남성연령대_60_이상_상주인구_수": "male_age_60_plus_resident_pop",
    "여성연령대_10_상주인구_수": "female_age_10_resident_pop",
    "여성연령대_20_상주인구_수": "female_age_20_resident_pop",
    "여성연령대_30_상주인구_수": "female_age_30_resident_pop",
    "여성연령대_40_상주인구_수": "female_age_40_resident_pop",
    "여성연령대_50_상주인구_수": "female_age_50_resident_pop",
    "여성연령대_60_이상_상주인구_수": "female_age_60_plus_resident_pop",
    "총_가구_수": "total_household_count",
    "아파트_가구_수": "apartment_household_count",
    "비_아파트_가구_수": "non_apartment_household_count",
}

WORKING_POPULATION_COLUMN_MAP: dict[str, str] = {
    "기준_년분기_코드": "year_quarter",
    "상권_구분_코드": "trdar_div_code",
    "상권_구분_코드_명": "trdar_div_name",
    "상권_코드": "trdar_code",
    "상권_코드_명": "trdar_name",
    "총_직장_인구_수": "total_working_pop",
    "남성_직장_인구_수": "male_working_pop",
    "여성_직장_인구_수": "female_working_pop",
    "연령대_10_직장_인구_수": "age_10_working_pop",
    "연령대_20_직장_인구_수": "age_20_working_pop",
    "연령대_30_직장_인구_수": "age_30_working_pop",
    "연령대_40_직장_인구_수": "age_40_working_pop",
    "연령대_50_직장_인구_수": "age_50_working_pop",
    "연령대_60_이상_직장_인구_수": "age_60_plus_working_pop",
    "남성연령대_10_직장_인구_수": "male_age_10_working_pop",
    "남성연령대_20_직장_인구_수": "male_age_20_working_pop",
    "남성연령대_30_직장_인구_수": "male_age_30_working_pop",
    "남성연령대_40_직장_인구_수": "male_age_40_working_pop",
    "남성연령대_50_직장_인구_수": "male_age_50_working_pop",
    "남성연령대_60_이상_직장_인구_수": "male_age_60_plus_working_pop",
    "여성연령대_10_직장_인구_수": "female_age_10_working_pop",
    "여성연령대_20_직장_인구_수": "female_age_20_working_pop",
    "여성연령대_30_직장_인구_수": "female_age_30_working_pop",
    "여성연령대_40_직장_인구_수": "female_age_40_working_pop",
    "여성연령대_50_직장_인구_수": "female_age_50_working_pop",
    "여성연령대_60_이상_직장_인구_수": "female_age_60_plus_working_pop",
}

CONSUMPTION_COLUMN_MAP: dict[str, str] = {
    "기준_년분기_코드": "year_quarter",
    "상권_구분_코드": "trdar_div_code",
    "상권_구분_코드_명": "trdar_div_name",
    "상권_코드": "trdar_code",
    "상권_코드_명": "trdar_name",
    "월_평균_소득_금액": "monthly_avg_income",
    "소득_구간_코드": "income_range_code",
    "지출_총금액": "total_expenditure",
    "식료품_지출_총금액": "food_expenditure",
    "의류_신발_지출_총금액": "clothing_expenditure",
    "생활용품_지출_총금액": "household_expenditure",
    "의료비_지출_총금액": "medical_expenditure",
    "교통_지출_총금액": "transport_expenditure",
    "여가_지출_총금액": "leisure_expenditure",
    "문화_지출_총금액": "culture_expenditure",
    "교육_지출_총금액": "education_expenditure",
    "유흥_지출_총금액": "entertainment_expenditure",
}

APARTMENT_COLUMN_MAP: dict[str, str] = {
    "기준_년분기_코드": "year_quarter",
    "상권_구분_코드": "trdar_div_code",
    "상권_구분_코드_명": "trdar_div_name",
    "상권_코드": "trdar_code",
    "상권_코드_명": "trdar_name",
    "아파트_단지_수": "complex_count",
    "아파트_면적_66_제곱미터_미만_세대_수": "area_under_66_count",
    "아파트_면적_66_제곱미터_세대_수": "area_66_count",
    "아파트_면적_99_제곱미터_세대_수": "area_99_count",
    "아파트_면적_132_제곱미터_세대_수": "area_132_count",
    "아파트_면적_165_제곱미터_세대_수": "area_165_count",
    "아파트_가격_1_억_미만_세대_수": "price_under_1b_count",
    "아파트_가격_1_억_세대_수": "price_1b_count",
    "아파트_가격_2_억_세대_수": "price_2b_count",
    "아파트_가격_3_억_세대_수": "price_3b_count",
    "아파트_가격_4_억_세대_수": "price_4b_count",
    "아파트_가격_5_억_세대_수": "price_5b_count",
    "아파트_가격_6_억_이상_세대_수": "price_over_6b_count",
    "아파트_평균_면적": "avg_area",
    "아파트_평균_시가": "avg_price",
}

COMMERCIAL_CHANGE_COLUMN_MAP: dict[str, str] = {
    "기준_년분기_코드": "year_quarter",
    "상권_구분_코드": "trdar_div_code",
    "상권_구분_코드_명": "trdar_div_name",
    "상권_코드": "trdar_code",
    "상권_코드_명": "trdar_name",
    "상권_변화_지표": "change_indicator",
    "상권_변화_지표_명": "change_indicator_name",
    "운영_영업_개월_평균": "operating_months_avg",
    "폐업_영업_개월_평균": "closure_months_avg",
    "서울_운영_영업_개월_평균": "seoul_operating_months_avg",
    "서울_폐업_영업_개월_평균": "seoul_closure_months_avg",
}
