"""add region column to estimated_sales

Revision ID: 0e6e5e114043
Revises: 2dd5bc6cfc6d
Create Date: 2026-05-20 17:45:33.063143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6e5e114043'
down_revision: Union[str, Sequence[str], None] = '2dd5bc6cfc6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('estimated_sales', sa.Column('region', sa.String(length=50), nullable=True))
    op.execute("UPDATE estimated_sales SET region = 'seoul'")
    op.alter_column('estimated_sales', 'region', nullable=False)
    op.drop_constraint(op.f('uq_estimated_sales'), 'estimated_sales', type_='unique')
    op.create_unique_constraint('uq_estimated_sales', 'estimated_sales', ['year_quarter', 'trdar_code', 'service_code', 'region'])
    op.create_index(op.f('ix_estimated_sales_region'), 'estimated_sales', ['region'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimated_sales_region'), table_name='estimated_sales')
    op.drop_constraint('uq_estimated_sales', 'estimated_sales', type_='unique')
    op.create_unique_constraint(op.f('uq_estimated_sales'), 'estimated_sales', ['year_quarter', 'trdar_code', 'service_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('estimated_sales', 'region')
    # ### end Alembic commands ###
