"""create_store_table

Revision ID: 0eab839f5717
Revises: 0e6e5e114043
Create Date: 2026-05-20 21:24:52.400066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eab839f5717'
down_revision: Union[str, Sequence[str], None] = '0e6e5e114043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('year_quarter', sa.Integer(), nullable=False),
    sa.Column('trdar_div_code', sa.String(), nullable=False),
    sa.Column('trdar_div_name', sa.String(), nullable=False),
    sa.Column('trdar_code', sa.Integer(), nullable=False),
    sa.Column('trdar_name', sa.String(), nullable=False),
    sa.Column('service_code', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('store_count', sa.Integer(), nullable=False),
    sa.Column('similar_industry_store_count', sa.Integer(), nullable=False),
    sa.Column('opening_rate', sa.Integer(), nullable=False),
    sa.Column('opening_store_count', sa.Integer(), nullable=False),
    sa.Column('closure_rate', sa.Integer(), nullable=False),
    sa.Column('closure_store_count', sa.Integer(), nullable=False),
    sa.Column('franchise_store_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_quarter', 'trdar_code', 'service_code', 'region', name='uq_store')
    )
    op.create_index(op.f('ix_store_region'), 'store', ['region'], unique=False)
    op.create_index(op.f('ix_store_service_code'), 'store', ['service_code'], unique=False)
    op.create_index(op.f('ix_store_trdar_code'), 'store', ['trdar_code'], unique=False)
    op.create_index(op.f('ix_store_year_quarter'), 'store', ['year_quarter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_year_quarter'), table_name='store')
    op.drop_index(op.f('ix_store_trdar_code'), table_name='store')
    op.drop_index(op.f('ix_store_service_code'), table_name='store')
    op.drop_index(op.f('ix_store_region'), table_name='store')
    op.drop_table('store')
    # ### end Alembic commands ###
