"""alter_apartment_nullable_cols

Revision ID: 163e92781731
Revises: 2b8efe31480b
Create Date: 2026-05-20 21:47:37.454459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163e92781731'
down_revision: Union[str, Sequence[str], None] = '2b8efe31480b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartment', 'area_under_66_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('apartment', 'price_under_1b_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('apartment', 'price_1b_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('apartment', 'price_2b_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartment', 'price_2b_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('apartment', 'price_1b_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('apartment', 'price_under_1b_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('apartment', 'area_under_66_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
