"""drop legacy area table

Revision ID: 2bdb926946a5
Revises: 98965c28cf3e
Create Date: 2026-07-01 16:55:56.419379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdb926946a5'
down_revision: Union[str, Sequence[str], None] = '98965c28cf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_area_region'), table_name='area')
    op.drop_index(op.f('ix_area_trdar_code'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trdar_div_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trdar_div_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trdar_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trdar_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('x_coord', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y_coord', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('district_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('district_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('adm_dong_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('adm_dong_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('area_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('area_pkey')),
    sa.UniqueConstraint('trdar_code', 'region', name=op.f('uq_area'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_area_trdar_code'), 'area', ['trdar_code'], unique=False)
    op.create_index(op.f('ix_area_region'), 'area', ['region'], unique=False)
    # ### end Alembic commands ###
