"""create estimated_sales table

Revision ID: 2dd5bc6cfc6d
Revises: 
Create Date: 2026-05-20 17:04:24.206287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd5bc6cfc6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimated_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_quarter', sa.Integer(), nullable=False),
    sa.Column('trdar_div_code', sa.String(), nullable=False),
    sa.Column('trdar_div_name', sa.String(), nullable=False),
    sa.Column('trdar_code', sa.Integer(), nullable=False),
    sa.Column('trdar_name', sa.String(), nullable=False),
    sa.Column('service_code', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('monthly_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('monthly_sales_count', sa.Integer(), nullable=False),
    sa.Column('weekday_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('weekend_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('mon_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('tue_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('wed_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('thu_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('fri_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('sat_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('sun_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('time_00_06_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('time_06_11_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('time_11_14_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('time_14_17_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('time_17_21_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('time_21_24_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('male_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('female_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('age_10_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('age_20_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('age_30_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('age_40_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('age_50_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('age_60_plus_sales_amount', sa.BigInteger(), nullable=False),
    sa.Column('weekday_sales_count', sa.Integer(), nullable=False),
    sa.Column('weekend_sales_count', sa.Integer(), nullable=False),
    sa.Column('mon_sales_count', sa.Integer(), nullable=False),
    sa.Column('tue_sales_count', sa.Integer(), nullable=False),
    sa.Column('wed_sales_count', sa.Integer(), nullable=False),
    sa.Column('thu_sales_count', sa.Integer(), nullable=False),
    sa.Column('fri_sales_count', sa.Integer(), nullable=False),
    sa.Column('sat_sales_count', sa.Integer(), nullable=False),
    sa.Column('sun_sales_count', sa.Integer(), nullable=False),
    sa.Column('time_00_06_sales_count', sa.Integer(), nullable=False),
    sa.Column('time_06_11_sales_count', sa.Integer(), nullable=False),
    sa.Column('time_11_14_sales_count', sa.Integer(), nullable=False),
    sa.Column('time_14_17_sales_count', sa.Integer(), nullable=False),
    sa.Column('time_17_21_sales_count', sa.Integer(), nullable=False),
    sa.Column('time_21_24_sales_count', sa.Integer(), nullable=False),
    sa.Column('male_sales_count', sa.Integer(), nullable=False),
    sa.Column('female_sales_count', sa.Integer(), nullable=False),
    sa.Column('age_10_sales_count', sa.Integer(), nullable=False),
    sa.Column('age_20_sales_count', sa.Integer(), nullable=False),
    sa.Column('age_30_sales_count', sa.Integer(), nullable=False),
    sa.Column('age_40_sales_count', sa.Integer(), nullable=False),
    sa.Column('age_50_sales_count', sa.Integer(), nullable=False),
    sa.Column('age_60_plus_sales_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_quarter', 'trdar_code', 'service_code', name='uq_estimated_sales')
    )
    op.create_index(op.f('ix_estimated_sales_service_code'), 'estimated_sales', ['service_code'], unique=False)
    op.create_index(op.f('ix_estimated_sales_trdar_code'), 'estimated_sales', ['trdar_code'], unique=False)
    op.create_index(op.f('ix_estimated_sales_year_quarter'), 'estimated_sales', ['year_quarter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimated_sales_year_quarter'), table_name='estimated_sales')
    op.drop_index(op.f('ix_estimated_sales_trdar_code'), table_name='estimated_sales')
    op.drop_index(op.f('ix_estimated_sales_service_code'), table_name='estimated_sales')
    op.drop_table('estimated_sales')
    # ### end Alembic commands ###
