"""create_remaining_7_tables

Revision ID: 5f60362a2f03
Revises: 0eab839f5717
Create Date: 2026-05-20 21:31:17.395019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f60362a2f03'
down_revision: Union[str, Sequence[str], None] = '0eab839f5717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('year_quarter', sa.Integer(), nullable=False),
    sa.Column('trdar_div_code', sa.String(), nullable=False),
    sa.Column('trdar_div_name', sa.String(), nullable=False),
    sa.Column('trdar_code', sa.Integer(), nullable=False),
    sa.Column('trdar_name', sa.String(), nullable=False),
    sa.Column('complex_count', sa.Integer(), nullable=False),
    sa.Column('area_under_66_count', sa.Integer(), nullable=False),
    sa.Column('area_66_count', sa.Integer(), nullable=True),
    sa.Column('area_99_count', sa.Integer(), nullable=True),
    sa.Column('area_132_count', sa.Integer(), nullable=True),
    sa.Column('area_165_count', sa.Integer(), nullable=True),
    sa.Column('price_under_1b_count', sa.Integer(), nullable=False),
    sa.Column('price_1b_count', sa.Integer(), nullable=False),
    sa.Column('price_2b_count', sa.Integer(), nullable=False),
    sa.Column('price_3b_count', sa.Integer(), nullable=True),
    sa.Column('price_4b_count', sa.Integer(), nullable=True),
    sa.Column('price_5b_count', sa.Integer(), nullable=True),
    sa.Column('price_over_6b_count', sa.Integer(), nullable=True),
    sa.Column('avg_area', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_quarter', 'trdar_code', 'region', name='uq_apartment')
    )
    op.create_index(op.f('ix_apartment_region'), 'apartment', ['region'], unique=False)
    op.create_index(op.f('ix_apartment_trdar_code'), 'apartment', ['trdar_code'], unique=False)
    op.create_index(op.f('ix_apartment_year_quarter'), 'apartment', ['year_quarter'], unique=False)
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('trdar_div_code', sa.String(), nullable=False),
    sa.Column('trdar_div_name', sa.String(), nullable=False),
    sa.Column('trdar_code', sa.Integer(), nullable=False),
    sa.Column('trdar_name', sa.String(), nullable=False),
    sa.Column('x_coord', sa.Integer(), nullable=False),
    sa.Column('y_coord', sa.Integer(), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(), nullable=False),
    sa.Column('adm_dong_code', sa.Integer(), nullable=False),
    sa.Column('adm_dong_name', sa.String(), nullable=False),
    sa.Column('area_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trdar_code', 'region', name='uq_area')
    )
    op.create_index(op.f('ix_area_region'), 'area', ['region'], unique=False)
    op.create_index(op.f('ix_area_trdar_code'), 'area', ['trdar_code'], unique=False)
    op.create_table('commercial_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('year_quarter', sa.Integer(), nullable=False),
    sa.Column('trdar_div_code', sa.String(), nullable=False),
    sa.Column('trdar_div_name', sa.String(), nullable=False),
    sa.Column('trdar_code', sa.Integer(), nullable=False),
    sa.Column('trdar_name', sa.String(), nullable=False),
    sa.Column('change_indicator', sa.String(), nullable=False),
    sa.Column('change_indicator_name', sa.String(), nullable=False),
    sa.Column('operating_months_avg', sa.Integer(), nullable=False),
    sa.Column('closure_months_avg', sa.Integer(), nullable=False),
    sa.Column('seoul_operating_months_avg', sa.Integer(), nullable=False),
    sa.Column('seoul_closure_months_avg', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_quarter', 'trdar_code', 'region', name='uq_commercial_change')
    )
    op.create_index(op.f('ix_commercial_change_region'), 'commercial_change', ['region'], unique=False)
    op.create_index(op.f('ix_commercial_change_trdar_code'), 'commercial_change', ['trdar_code'], unique=False)
    op.create_index(op.f('ix_commercial_change_year_quarter'), 'commercial_change', ['year_quarter'], unique=False)
    op.create_table('consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('year_quarter', sa.Integer(), nullable=False),
    sa.Column('trdar_div_code', sa.String(), nullable=False),
    sa.Column('trdar_div_name', sa.String(), nullable=False),
    sa.Column('trdar_code', sa.Integer(), nullable=False),
    sa.Column('trdar_name', sa.String(), nullable=False),
    sa.Column('monthly_avg_income', sa.Float(), nullable=False),
    sa.Column('income_range_code', sa.Integer(), nullable=False),
    sa.Column('total_expenditure', sa.Float(), nullable=False),
    sa.Column('food_expenditure', sa.Float(), nullable=False),
    sa.Column('clothing_expenditure', sa.Float(), nullable=False),
    sa.Column('household_expenditure', sa.Float(), nullable=False),
    sa.Column('medical_expenditure', sa.Float(), nullable=False),
    sa.Column('transport_expenditure', sa.Float(), nullable=False),
    sa.Column('leisure_expenditure', sa.Float(), nullable=False),
    sa.Column('culture_expenditure', sa.Float(), nullable=False),
    sa.Column('education_expenditure', sa.Float(), nullable=False),
    sa.Column('entertainment_expenditure', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_quarter', 'trdar_code', 'region', name='uq_consumption')
    )
    op.create_index(op.f('ix_consumption_region'), 'consumption', ['region'], unique=False)
    op.create_index(op.f('ix_consumption_trdar_code'), 'consumption', ['trdar_code'], unique=False)
    op.create_index(op.f('ix_consumption_year_quarter'), 'consumption', ['year_quarter'], unique=False)
    op.create_table('floating_population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('year_quarter', sa.Integer(), nullable=False),
    sa.Column('trdar_div_code', sa.String(), nullable=False),
    sa.Column('trdar_div_name', sa.String(), nullable=False),
    sa.Column('trdar_code', sa.Integer(), nullable=False),
    sa.Column('trdar_name', sa.String(), nullable=False),
    sa.Column('total_floating_pop', sa.Integer(), nullable=False),
    sa.Column('male_floating_pop', sa.Integer(), nullable=False),
    sa.Column('female_floating_pop', sa.Integer(), nullable=False),
    sa.Column('age_10_floating_pop', sa.Integer(), nullable=False),
    sa.Column('age_20_floating_pop', sa.Integer(), nullable=False),
    sa.Column('age_30_floating_pop', sa.Integer(), nullable=False),
    sa.Column('age_40_floating_pop', sa.Integer(), nullable=False),
    sa.Column('age_50_floating_pop', sa.Integer(), nullable=False),
    sa.Column('age_60_plus_floating_pop', sa.Integer(), nullable=False),
    sa.Column('time_00_06_floating_pop', sa.Integer(), nullable=False),
    sa.Column('time_06_11_floating_pop', sa.Integer(), nullable=False),
    sa.Column('time_11_14_floating_pop', sa.Integer(), nullable=False),
    sa.Column('time_14_17_floating_pop', sa.Integer(), nullable=False),
    sa.Column('time_17_21_floating_pop', sa.Integer(), nullable=False),
    sa.Column('time_21_24_floating_pop', sa.Integer(), nullable=False),
    sa.Column('mon_floating_pop', sa.Integer(), nullable=False),
    sa.Column('tue_floating_pop', sa.Integer(), nullable=False),
    sa.Column('wed_floating_pop', sa.Integer(), nullable=False),
    sa.Column('thu_floating_pop', sa.Integer(), nullable=False),
    sa.Column('fri_floating_pop', sa.Integer(), nullable=False),
    sa.Column('sat_floating_pop', sa.Integer(), nullable=False),
    sa.Column('sun_floating_pop', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_quarter', 'trdar_code', 'region', name='uq_floating_population')
    )
    op.create_index(op.f('ix_floating_population_region'), 'floating_population', ['region'], unique=False)
    op.create_index(op.f('ix_floating_population_trdar_code'), 'floating_population', ['trdar_code'], unique=False)
    op.create_index(op.f('ix_floating_population_year_quarter'), 'floating_population', ['year_quarter'], unique=False)
    op.create_table('resident_population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('year_quarter', sa.Integer(), nullable=False),
    sa.Column('trdar_div_code', sa.String(), nullable=False),
    sa.Column('trdar_div_name', sa.String(), nullable=False),
    sa.Column('trdar_code', sa.Integer(), nullable=False),
    sa.Column('trdar_name', sa.String(), nullable=False),
    sa.Column('total_resident_pop', sa.Integer(), nullable=False),
    sa.Column('male_resident_pop', sa.Integer(), nullable=False),
    sa.Column('female_resident_pop', sa.Integer(), nullable=False),
    sa.Column('age_10_resident_pop', sa.Integer(), nullable=False),
    sa.Column('age_20_resident_pop', sa.Integer(), nullable=False),
    sa.Column('age_30_resident_pop', sa.Integer(), nullable=False),
    sa.Column('age_40_resident_pop', sa.Integer(), nullable=False),
    sa.Column('age_50_resident_pop', sa.Integer(), nullable=False),
    sa.Column('age_60_plus_resident_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_10_resident_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_20_resident_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_30_resident_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_40_resident_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_50_resident_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_60_plus_resident_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_10_resident_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_20_resident_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_30_resident_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_40_resident_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_50_resident_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_60_plus_resident_pop', sa.Integer(), nullable=False),
    sa.Column('total_household_count', sa.Integer(), nullable=False),
    sa.Column('apartment_household_count', sa.Integer(), nullable=False),
    sa.Column('non_apartment_household_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_quarter', 'trdar_code', 'region', name='uq_resident_population')
    )
    op.create_index(op.f('ix_resident_population_region'), 'resident_population', ['region'], unique=False)
    op.create_index(op.f('ix_resident_population_trdar_code'), 'resident_population', ['trdar_code'], unique=False)
    op.create_index(op.f('ix_resident_population_year_quarter'), 'resident_population', ['year_quarter'], unique=False)
    op.create_table('working_population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('year_quarter', sa.Integer(), nullable=False),
    sa.Column('trdar_div_code', sa.String(), nullable=False),
    sa.Column('trdar_div_name', sa.String(), nullable=False),
    sa.Column('trdar_code', sa.Integer(), nullable=False),
    sa.Column('trdar_name', sa.String(), nullable=False),
    sa.Column('total_working_pop', sa.Integer(), nullable=False),
    sa.Column('male_working_pop', sa.Integer(), nullable=False),
    sa.Column('female_working_pop', sa.Integer(), nullable=False),
    sa.Column('age_10_working_pop', sa.Integer(), nullable=False),
    sa.Column('age_20_working_pop', sa.Integer(), nullable=False),
    sa.Column('age_30_working_pop', sa.Integer(), nullable=False),
    sa.Column('age_40_working_pop', sa.Integer(), nullable=False),
    sa.Column('age_50_working_pop', sa.Integer(), nullable=False),
    sa.Column('age_60_plus_working_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_10_working_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_20_working_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_30_working_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_40_working_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_50_working_pop', sa.Integer(), nullable=False),
    sa.Column('male_age_60_plus_working_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_10_working_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_20_working_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_30_working_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_40_working_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_50_working_pop', sa.Integer(), nullable=False),
    sa.Column('female_age_60_plus_working_pop', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_quarter', 'trdar_code', 'region', name='uq_working_population')
    )
    op.create_index(op.f('ix_working_population_region'), 'working_population', ['region'], unique=False)
    op.create_index(op.f('ix_working_population_trdar_code'), 'working_population', ['trdar_code'], unique=False)
    op.create_index(op.f('ix_working_population_year_quarter'), 'working_population', ['year_quarter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_population_year_quarter'), table_name='working_population')
    op.drop_index(op.f('ix_working_population_trdar_code'), table_name='working_population')
    op.drop_index(op.f('ix_working_population_region'), table_name='working_population')
    op.drop_table('working_population')
    op.drop_index(op.f('ix_resident_population_year_quarter'), table_name='resident_population')
    op.drop_index(op.f('ix_resident_population_trdar_code'), table_name='resident_population')
    op.drop_index(op.f('ix_resident_population_region'), table_name='resident_population')
    op.drop_table('resident_population')
    op.drop_index(op.f('ix_floating_population_year_quarter'), table_name='floating_population')
    op.drop_index(op.f('ix_floating_population_trdar_code'), table_name='floating_population')
    op.drop_index(op.f('ix_floating_population_region'), table_name='floating_population')
    op.drop_table('floating_population')
    op.drop_index(op.f('ix_consumption_year_quarter'), table_name='consumption')
    op.drop_index(op.f('ix_consumption_trdar_code'), table_name='consumption')
    op.drop_index(op.f('ix_consumption_region'), table_name='consumption')
    op.drop_table('consumption')
    op.drop_index(op.f('ix_commercial_change_year_quarter'), table_name='commercial_change')
    op.drop_index(op.f('ix_commercial_change_trdar_code'), table_name='commercial_change')
    op.drop_index(op.f('ix_commercial_change_region'), table_name='commercial_change')
    op.drop_table('commercial_change')
    op.drop_index(op.f('ix_area_trdar_code'), table_name='area')
    op.drop_index(op.f('ix_area_region'), table_name='area')
    op.drop_table('area')
    op.drop_index(op.f('ix_apartment_year_quarter'), table_name='apartment')
    op.drop_index(op.f('ix_apartment_trdar_code'), table_name='apartment')
    op.drop_index(op.f('ix_apartment_region'), table_name='apartment')
    op.drop_table('apartment')
    # ### end Alembic commands ###
