"""normalize market to 3NF (dims + lean facts)

Revision ID: 98965c28cf3e
Revises: c2d3e4f5a6b7
Create Date: 2026-07-01 16:25:30.210445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98965c28cf3e'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_indicator',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('region',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('x_coord', sa.Integer(), nullable=True),
    sa.Column('y_coord', sa.Integer(), nullable=True),
    sa.Column('area_size', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_code'], ['region.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_region_parent_code'), 'region', ['parent_code'], unique=False)
    op.create_table('service_category',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('trade_area_division',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('trade_area',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('division_code', sa.String(length=2), nullable=False),
    sa.Column('region_code', sa.String(length=20), nullable=True),
    sa.Column('x_coord', sa.Integer(), nullable=False),
    sa.Column('y_coord', sa.Integer(), nullable=False),
    sa.Column('area_size', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['division_code'], ['trade_area_division.code'], ),
    sa.ForeignKeyConstraint(['region_code'], ['region.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_trade_area_division_code'), 'trade_area', ['division_code'], unique=False)
    op.create_index(op.f('ix_trade_area_region_code'), 'trade_area', ['region_code'], unique=False)
    op.drop_index(op.f('ix_apartment_region'), table_name='apartment')
    op.drop_constraint(op.f('uq_apartment'), 'apartment', type_='unique')
    op.create_unique_constraint('uq_apartment', 'apartment', ['year_quarter', 'trdar_code'])
    op.create_foreign_key(None, 'apartment', 'trade_area', ['trdar_code'], ['code'])
    op.drop_column('apartment', 'region')
    op.drop_column('apartment', 'trdar_name')
    op.drop_column('apartment', 'trdar_div_name')
    op.drop_column('apartment', 'trdar_div_code')
    op.drop_index(op.f('ix_commercial_change_region'), table_name='commercial_change')
    op.drop_constraint(op.f('uq_commercial_change'), 'commercial_change', type_='unique')
    op.create_unique_constraint('uq_commercial_change', 'commercial_change', ['year_quarter', 'trdar_code'])
    op.create_foreign_key(None, 'commercial_change', 'change_indicator', ['change_indicator'], ['code'])
    op.create_foreign_key(None, 'commercial_change', 'trade_area', ['trdar_code'], ['code'])
    op.drop_column('commercial_change', 'trdar_div_name')
    op.drop_column('commercial_change', 'change_indicator_name')
    op.drop_column('commercial_change', 'region')
    op.drop_column('commercial_change', 'trdar_name')
    op.drop_column('commercial_change', 'trdar_div_code')
    op.drop_index(op.f('ix_consumption_region'), table_name='consumption')
    op.drop_constraint(op.f('uq_consumption'), 'consumption', type_='unique')
    op.create_unique_constraint('uq_consumption', 'consumption', ['year_quarter', 'trdar_code'])
    op.create_foreign_key(None, 'consumption', 'trade_area', ['trdar_code'], ['code'])
    op.drop_column('consumption', 'region')
    op.drop_column('consumption', 'trdar_name')
    op.drop_column('consumption', 'trdar_div_name')
    op.drop_column('consumption', 'trdar_div_code')
    op.drop_index(op.f('ix_estimated_sales_region'), table_name='estimated_sales')
    op.drop_constraint(op.f('uq_estimated_sales'), 'estimated_sales', type_='unique')
    op.create_unique_constraint('uq_estimated_sales', 'estimated_sales', ['year_quarter', 'trdar_code', 'service_code'])
    op.create_foreign_key(None, 'estimated_sales', 'trade_area', ['trdar_code'], ['code'])
    op.create_foreign_key(None, 'estimated_sales', 'service_category', ['service_code'], ['code'])
    op.drop_column('estimated_sales', 'trdar_div_name')
    op.drop_column('estimated_sales', 'trdar_name')
    op.drop_column('estimated_sales', 'region')
    op.drop_column('estimated_sales', 'trdar_div_code')
    op.drop_column('estimated_sales', 'service_name')
    op.drop_index(op.f('ix_floating_population_region'), table_name='floating_population')
    op.drop_constraint(op.f('uq_floating_population'), 'floating_population', type_='unique')
    op.create_unique_constraint('uq_floating_population', 'floating_population', ['year_quarter', 'trdar_code'])
    op.create_foreign_key(None, 'floating_population', 'trade_area', ['trdar_code'], ['code'])
    op.drop_column('floating_population', 'region')
    op.drop_column('floating_population', 'trdar_name')
    op.drop_column('floating_population', 'trdar_div_name')
    op.drop_column('floating_population', 'trdar_div_code')
    op.drop_index(op.f('ix_resident_population_region'), table_name='resident_population')
    op.drop_constraint(op.f('uq_resident_population'), 'resident_population', type_='unique')
    op.create_unique_constraint('uq_resident_population', 'resident_population', ['year_quarter', 'trdar_code'])
    op.create_foreign_key(None, 'resident_population', 'trade_area', ['trdar_code'], ['code'])
    op.drop_column('resident_population', 'region')
    op.drop_column('resident_population', 'trdar_name')
    op.drop_column('resident_population', 'trdar_div_name')
    op.drop_column('resident_population', 'trdar_div_code')
    op.drop_index(op.f('ix_store_region'), table_name='store')
    op.drop_constraint(op.f('uq_store'), 'store', type_='unique')
    op.create_unique_constraint('uq_store', 'store', ['year_quarter', 'trdar_code', 'service_code'])
    op.create_foreign_key(None, 'store', 'trade_area', ['trdar_code'], ['code'])
    op.create_foreign_key(None, 'store', 'service_category', ['service_code'], ['code'])
    op.drop_column('store', 'trdar_div_name')
    op.drop_column('store', 'region')
    op.drop_column('store', 'trdar_name')
    op.drop_column('store', 'trdar_div_code')
    op.drop_column('store', 'service_name')
    op.drop_index(op.f('ix_working_population_region'), table_name='working_population')
    op.drop_constraint(op.f('uq_working_population'), 'working_population', type_='unique')
    op.create_unique_constraint('uq_working_population', 'working_population', ['year_quarter', 'trdar_code'])
    op.create_foreign_key(None, 'working_population', 'trade_area', ['trdar_code'], ['code'])
    op.drop_column('working_population', 'region')
    op.drop_column('working_population', 'trdar_name')
    op.drop_column('working_population', 'trdar_div_name')
    op.drop_column('working_population', 'trdar_div_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_population', sa.Column('trdar_div_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('working_population', sa.Column('trdar_div_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('working_population', sa.Column('trdar_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('working_population', sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'working_population', type_='foreignkey')
    op.drop_constraint('uq_working_population', 'working_population', type_='unique')
    op.create_unique_constraint(op.f('uq_working_population'), 'working_population', ['year_quarter', 'trdar_code', 'region'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_working_population_region'), 'working_population', ['region'], unique=False)
    op.add_column('store', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('store', sa.Column('trdar_div_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('store', sa.Column('trdar_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('store', sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('store', sa.Column('trdar_div_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.drop_constraint('uq_store', 'store', type_='unique')
    op.create_unique_constraint(op.f('uq_store'), 'store', ['year_quarter', 'trdar_code', 'service_code', 'region'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_store_region'), 'store', ['region'], unique=False)
    op.add_column('resident_population', sa.Column('trdar_div_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('resident_population', sa.Column('trdar_div_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('resident_population', sa.Column('trdar_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('resident_population', sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resident_population', type_='foreignkey')
    op.drop_constraint('uq_resident_population', 'resident_population', type_='unique')
    op.create_unique_constraint(op.f('uq_resident_population'), 'resident_population', ['year_quarter', 'trdar_code', 'region'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_resident_population_region'), 'resident_population', ['region'], unique=False)
    op.add_column('floating_population', sa.Column('trdar_div_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('floating_population', sa.Column('trdar_div_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('floating_population', sa.Column('trdar_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('floating_population', sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'floating_population', type_='foreignkey')
    op.drop_constraint('uq_floating_population', 'floating_population', type_='unique')
    op.create_unique_constraint(op.f('uq_floating_population'), 'floating_population', ['year_quarter', 'trdar_code', 'region'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_floating_population_region'), 'floating_population', ['region'], unique=False)
    op.add_column('estimated_sales', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('estimated_sales', sa.Column('trdar_div_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('estimated_sales', sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('estimated_sales', sa.Column('trdar_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('estimated_sales', sa.Column('trdar_div_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'estimated_sales', type_='foreignkey')
    op.drop_constraint(None, 'estimated_sales', type_='foreignkey')
    op.drop_constraint('uq_estimated_sales', 'estimated_sales', type_='unique')
    op.create_unique_constraint(op.f('uq_estimated_sales'), 'estimated_sales', ['year_quarter', 'trdar_code', 'service_code', 'region'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_estimated_sales_region'), 'estimated_sales', ['region'], unique=False)
    op.add_column('consumption', sa.Column('trdar_div_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('consumption', sa.Column('trdar_div_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('consumption', sa.Column('trdar_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('consumption', sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'consumption', type_='foreignkey')
    op.drop_constraint('uq_consumption', 'consumption', type_='unique')
    op.create_unique_constraint(op.f('uq_consumption'), 'consumption', ['year_quarter', 'trdar_code', 'region'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_consumption_region'), 'consumption', ['region'], unique=False)
    op.add_column('commercial_change', sa.Column('trdar_div_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('commercial_change', sa.Column('trdar_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('commercial_change', sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('commercial_change', sa.Column('change_indicator_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('commercial_change', sa.Column('trdar_div_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'commercial_change', type_='foreignkey')
    op.drop_constraint(None, 'commercial_change', type_='foreignkey')
    op.drop_constraint('uq_commercial_change', 'commercial_change', type_='unique')
    op.create_unique_constraint(op.f('uq_commercial_change'), 'commercial_change', ['year_quarter', 'trdar_code', 'region'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_commercial_change_region'), 'commercial_change', ['region'], unique=False)
    op.add_column('apartment', sa.Column('trdar_div_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('apartment', sa.Column('trdar_div_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('apartment', sa.Column('trdar_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('apartment', sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'apartment', type_='foreignkey')
    op.drop_constraint('uq_apartment', 'apartment', type_='unique')
    op.create_unique_constraint(op.f('uq_apartment'), 'apartment', ['year_quarter', 'trdar_code', 'region'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_apartment_region'), 'apartment', ['region'], unique=False)
    op.drop_index(op.f('ix_trade_area_region_code'), table_name='trade_area')
    op.drop_index(op.f('ix_trade_area_division_code'), table_name='trade_area')
    op.drop_table('trade_area')
    op.drop_table('trade_area_division')
    op.drop_table('service_category')
    op.drop_index(op.f('ix_region_parent_code'), table_name='region')
    op.drop_table('region')
    op.drop_table('change_indicator')
    # ### end Alembic commands ###
